# Generated by Django 6.0.1 on 2026-02-09 14:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0005_alter_activitylog_options_alter_budgetalert_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Machine-readable key, e.g. 'transport', 'licenses'", unique=True)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Material Transport'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category covers')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Brief description of the expense', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount spent', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense_date', models.DateField(help_text='Date when expense was incurred')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('payee', models.CharField(blank=True, help_text='Who was paid (vendor, government office, etc.)', max_length=200)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference, receipt number, or invoice number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('has_receipt', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring expense?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='expenses.expensecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='tracker.project')),
            ],
            options={
                'verbose_name_plural': 'Expense Entries',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/expenses/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.expenseentry')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Receipts',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
