# Generated by Django 6.0.1 on 2026-02-07 08:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0005_alter_activitylog_options_alter_budgetalert_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Machine-readable key, e.g. 'mason', 'carpenter'", unique=True)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Mason'", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Labor Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('number_of_workers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_per_worker_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='labor.laborcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='tracker.project')),
            ],
            options={
                'verbose_name_plural': 'Labor Entries',
                'ordering': ['-work_date', '-created_at'],
                'unique_together': {('project', 'category', 'work_date')},
            },
        ),
    ]
