# Generated by Django 6.0.1 on 2026-02-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        ('tracker', '0005_alter_activitylog_options_alter_budgetalert_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborentry',
            unique_together={('project', 'category', 'work_date', 'created_at')},
        ),
    ]
