# Generated by Django 6.0.1 on 2026-08-19 17:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_alter_laborentry_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborentry',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days worked at this rate', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='LaborReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/labor/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('labor_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='labor.laborentry')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Labor Receipts',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
