# Generated by Django 6.0.1 on 2026-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0003_laborentry_number_of_days_laborreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborentry',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction reference, receipt number, or invoice number', max_length=100),
        ),
    ]
