# Generated by Django 6.0.1 on 2026-01-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-is_primary', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as primary receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this receipt'),
        ),
    ]
