# Generated by Django 6.0.1 on 2026-02-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='material_entries', to='tracker.materialcategory'),
            preserve_default=False,
        ),
    ]
