# Generated by Django 6.0.1 on 2026-02-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_materialentry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatematerial',
            name='material_type',
        ),
        migrations.AddField(
            model_name='templatematerial',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='template_materials', to='tracker.materialcategory'),
            preserve_default=False,
        ),
    ]
