# Generated by Django 6.0.1 on 2026-01-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_receipt_options_receipt_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='material_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tracker.materialentry'),
        ),
    ]
