# Generated by Django 6.0.1 on 2026-02-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_templatematerial_material_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatematerial',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='templatematerial',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='template_materials', to='tracker.materialunit'),
            preserve_default=False,
        ),
    ]
