# Generated by Django 6.0.1 on 2026-02-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_templatematerial_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='budgetalert',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Budget Alerts'},
        ),
        migrations.AlterModelOptions(
            name='materialcatalog',
            options={'ordering': ['category__name', 'description'], 'verbose_name_plural': 'Material Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Material Categories'},
        ),
        migrations.AlterModelOptions(
            name='materialentry',
            options={'ordering': ['-purchase_date', '-created_at'], 'verbose_name_plural': 'Material Entries'},
        ),
        migrations.AlterModelOptions(
            name='materialunit',
            options={'ordering': ['name'], 'verbose_name_plural': ['Material Units']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectphoto',
            options={'ordering': ['-taken_date', '-uploaded_at'], 'verbose_name_plural': 'Project Photos'},
        ),
        migrations.AlterModelOptions(
            name='projecttemplate',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Project Templates'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-is_primary', '-uploaded_at'], 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AlterModelOptions(
            name='templatematerial',
            options={'verbose_name_plural': 'Template Materials'},
        ),
    ]
