# Generated by Django 6.0.1 on 2026-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_activitylog_options_alter_budgetalert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction reference, receipt number, or invoice number', max_length=100),
        ),
    ]
